export interface Work {
  title_preview:string,
  subtitle_fr:string,
  subtitle_en:string,
  url:string,
  img_preview:string,
  img1:string,
  all_img:Array<string>,
  all_tags:Array<string>,
  website:string,
  behance:string,
  github:string,
  description_en: string,
  description_fr:string,
  type:number,
}
