export interface Work {
  title_preview:string,
  subtitle_fr:string,
  subtitle_en:string,
  url:string,
  img_preview:string,
  img1:string,
  all_img:Array<string>,
  all_tags:Array<string>,
  website:string,
  behance:string,
  github:string,
  description_en:string,
  description_fr:string,
  type:number,
  wireframe_description_fr:string,
  wireframe_description_en:string,
  wireframe_image: string,
  designsystem_description_fr: string,
  designsystem_description_en: string,
  designsystem_image: string,
  mockups_description_fr: string,
  mockups_description_en: string,
  mockups_image: string,
  dev_description_fr: string,
  dev_description_en: string,
  dev_image: string,
  conclusion_description_fr: string,
  conclusion_description_en: string,
}
